# no touchy
file-version: 1

# Put your Discord token here:
discord-token:

imagemaps:
  # Channels that allow processing of attachments to be saved into the imagemaps images folder
  channels:
  # - 0123456789
  # - 01248163264128256
  # Path to the folder where image files will be saved
  path: "plugins/ImageMaps/images/"
  # responds to the user in channel message is sent (default to true)
  reply: true
  # logs debug messages in console
  debug: false

